In [1]:
import pandas as pd
df = pd.read_excel("/content/institutions-and-researchers.xlsx")
df.head()

#Verificar colunas com valores nulos
num_nulos = df.isnull().sum()
print(f'Valores nulos no DataSet: {num_nulos}')

#Verificar valores duplicados
num_duplicadas = df.duplicated().sum()
print(f"Valores Duplicados no Dataset: {num_duplicadas}")

#Corrigindo valore em novo dataset
df_novo = df
df_novo = df_novo.drop_duplicates()
num_duplicads = df_novo.duplicated().sum()
df_novo['Research Name'] = df_novo['Research Name'].fillna("Anomyous")

print(f"Valores Duplicados no novo Dataset: {num_duplicads}")
print("Novo Dataset:")
display(df_novo.iloc[340:360, 0])

Valores nulos no DataSet: Research Name             2
University / Institute    0
Country                   0
dtype: int64
Valores Duplicados no Dataset: 1
Valores Duplicados no novo Dataset: 0
Novo Dataset:

/tmp/ipykernel_729/676714415.py:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_novo['Research Name'] = df_novo['Research Name'].fillna("Anomyous")

341               Samsul Khabib
342          Yasir S. Alsalamah
343        Bander Saad Albagawi
344                Lisa Babkair
345             Ibrahim Alasqah
346         Talal Ali F Alharbi
347                    Anomyous
348               Nada Alqarawi
349      Hana Khaled ALOtheimin
350        Faisal I. Almohaileb
351             Thamer Alslamah
352    Monerh Abdullah Alfalaij
353                    Anomyous
354              Isabel Coetzee
355          Mona Gamal Mohamed
356                Esin Kavuran
357                  Ziya Polat
358              Aybike Bahçeli
359               Alexei Sammut
360                 Ahmad Rayan
Name: Research Name, dtype: object

##Separando Tabelas, Criando IDs e Relacionamentos

In [11]:
#Criando chaves de ID:
df_novo['researcher_id'] = range(1, len(df_novo) + 1)
agrupamento = df_novo[['University / Institute', 'Country']].apply(tuple, axis=1) #considerando combinações únicas de instituição e pais
df_novo['institution_id'] = pd.factorize(agrupamento)[0] #filias em diferentes paises são tidas como instituições diferentes
print("Novo Dataset:")
display(df_novo)

#Criando Tabela de Instituições
df_institutions = df_novo[['University / Institute', 'Country', 'institution_id']].copy()
print("Tabela Instituições:")
display(df_institutions)

#Criando tabela de Pesquisadores
df_researchers = df_novo[['Research Name', 'researcher_id', 'institution_id']].copy()
print("Tabela Pesquisadores:")
display(df_researchers)

Novo Dataset:

/tmp/ipykernel_729/257744656.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_novo['researcher_id'] = range(1, len(df_novo) + 1)
/tmp/ipykernel_729/257744656.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_novo['institution_id'] = pd.factorize(agrupamento)[0] #filias em diferentes paises são tidas como instituições diferentes

,Research Name,University / Institute,Country,researcher_id,institution_id
0,Danilo Rodrigues Pereira,"University of Campinas (UNICAMP), Brazil",Brazil,1,0
1,Simone Appenzeller,"University of Campinas (UNICAMP), Brazil",Brazil,2,0
2,André Franceschi de Angelis,"University of Campinas (UNICAMP), Brazil",Brazil,3,0
3,Thais Rocha,"University of Campinas (UNICAMP), Brazil",Brazil,4,0
4,Danielle F. dos Santos Dias,"University of Campinas (UNICAMP), Brazil",Brazil,5,0
...,...,...,...,...,...
389,Imam Much Ibnu Subroto,"Universitas Islam Sultan Agung, Indonesia",Indonesia,389,243
390,Ir. Suryani Alifah,"Universitas Islam Sultan Agung, Indonesia",Indonesia,390,243
391,Ira Puspitasari,Universitas Airlangga - Indonesia,Indonesia,391,244
392,Barry Nuqoba,Universitas Airlangga - Indonesia,Indonesia,392,244
393,Nania Nuzulita,Universitas Airlangga - Indonesia,Indonesia,393,244

Tabela Instituições:

                        University / Institute    Country  institution_id
0     University of Campinas (UNICAMP), Brazil     Brazil               0
1     University of Campinas (UNICAMP), Brazil     Brazil               0
2     University of Campinas (UNICAMP), Brazil     Brazil               0
3     University of Campinas (UNICAMP), Brazil     Brazil               0
4     University of Campinas (UNICAMP), Brazil     Brazil               0
..                                         ...        ...             ...
389  Universitas Islam Sultan Agung, Indonesia  Indonesia             243
390  Universitas Islam Sultan Agung, Indonesia  Indonesia             243
391          Universitas Airlangga - Indonesia  Indonesia             244
392          Universitas Airlangga - Indonesia  Indonesia             244
393          Universitas Airlangga - Indonesia  Indonesia             244

[393 rows x 3 columns]

Tabela Pesquisadores:

                   Research Name  researcher_id  institution_id
0      Danilo Rodrigues Pereira               1               0
1             Simone Appenzeller              2               0
2    André Franceschi de Angelis              3               0
3                    Thais Rocha              4               0
4    Danielle F. dos Santos Dias              5               0
..                           ...            ...             ...
389       Imam Much Ibnu Subroto            389             243
390           Ir. Suryani Alifah            390             243
391              Ira Puspitasari            391             244
392                 Barry Nuqoba            392             244
393               Nania Nuzulita            393             244

[393 rows x 3 columns]

##Removendo isntituições duplicadas

In [12]:
instituions_duplicates = df_institutions.duplicated().sum()
print(f"Numero de instituições duplicadas: {instituions_duplicates}")
df_institutions = df_institutions.drop_duplicates()
display(df_institutions)

Numero de instituições duplicadas: 148

,University / Institute,Country,institution_id
0,"University of Campinas (UNICAMP), Brazil",Brazil,0
7,"Federal University of Southern Bahia (UFSB), B...",Brazil,1
8,Paulista University (UNIP) - Brazil,Brazil,2
10,Federal University of Maranhão (UFMA) - Brazil,Brazil,3
11,Federal University of Rio Grande do Sul (UFRGS)\n,Brazil,4
...,...,...,...
384,"STKIP PGRI Trenggalek, Indonesia",Indonesia,240
385,"Czech University of Life Sciences Prague, Czec...",Czech Republic,241
386,Mindanao State University - Iligan Institute o...,Philippines,242
388,"Universitas Islam Sultan Agung, Indonesia",Indonesia,243
391,Universitas Airlangga - Indonesia,Indonesia,244

In [13]:
#Exportando novas tabelas
df_institutions.to_csv('institutions.csv', index=False, encoding='utf-8')
df_researchers.to_csv('researchers.csv', index=False, encoding='utf-8')